serve:
  public:
    base_url: http://127.0.0.1:4433/
  admin:
    base_url: http://kratos:4434/

selfservice:
  default_browser_return_url: http://127.0.0.1:3000/
  whitelisted_return_urls:
    - http://127.0.0.1:3000/
    - http://127.0.0.1:3000/hydra/login

  methods:
    password:
      enabled: true
    link:
      config:
        lifespan: 1h
        base_url: http://127.0.0.1:3000/

  flows:
    settings:
      ui_url: http://127.0.0.1:3000/settings

    verification:
      ui_url: http://127.0.0.1:3000/verification
      enabled: true
      after:
        default_browser_return_url: http://127.0.0.1:3000/


    recovery:
      ui_url: http://127.0.0.1:3000/recovery
      enabled: true

    logout:
      after:
        default_browser_return_url: http://127.0.0.1:3000/login

    login:
      ui_url: http://127.0.0.1:3000/login

    registration:
      ui_url: http://127.0.0.1:3000/registration
      after:
        password:
          hooks:
            -
              hook: session

log:
  level: debug

hashers:
  algorithm: bcrypt
  bcrypt:
    cost: 8

identity:
  default_schema_url: file:///etc/config/kratos/identity.schema.json

courier:
  smtp:
    connection_uri: smtps://test:test@mailslurper:1025/?skip_ssl_verify=true
